title = "Eduard Aymerich"
author = "Eduard Aymerich"
languageCode = "en-us"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
paginate = 10

theme = "eduayme"
baseURL = "https://eduayme.github.io/"
publishDir = "docs"

[params]
    author = "Eduard Aymerich"
    cv = "https://drive.google.com/file/d/19pngaaUIYw64qDwDtYOzwMM6Wug5ohH8/view?usp=sharing"
    linkedin = "https://linkedin.com/in/eduayme"
    github = "https://github.com/eduayme"
    instagram = ""
    uplabs = ""
    dribble = ""
    codepen = ""

[menu]
    [[menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
        weight = 2
    [[menu.main]]
        identifier = "portfolio"
        name = "portfolio"
        url = "/portfolio"
        weight = 3
    [[menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/blog"
        weight = 4
    [[menu.main]]
        identifier = "contact"
        name = "contact"
        url = "/contact"
        weight = 5
